### ISSUE TITLE
500 error on metric scraping

### ISSUE THREAD

**Issue by gfthybridlabs** [mcelep/opa-scorecard#1]
Hi,

Thought I would give this a try as it seems interesting but when running I get  500 errors:-

```
# k get svc -n monitoring
opa-exporter                          ClusterIP   192.168.66.0      <none>        9141/TCP   49m

# k exec -it prometheus-monitoring-prometheus-0 -n monitoring -- /bin/sh -il
/prometheus $ wget -O - http://192.168.66.0:9141/metrics
Connecting to 192.168.66.0:9141 (192.168.66.0:9141)
wget: server returned error: HTTP/1.1 500 Internal Server Error
/prometheus $
```

The OPA Exporter pod logs show these being scraped:-
```
2021/06/28 11:24:22 Kind:AllowedServicePortName, Name:port-name-constraint, Namespace:
2021/06/28 11:24:22 Kind:K8sPSPAllowPrivilegeEscalationContainer, Name:psp-allow-privilege-escalation-container, Namespace:
2021/06/28 11:24:22 Kind:K8sPSPPrivilegedContainer, Name:psp-privileged-container, Namespace:
2021/06/28 11:24:22 Kind:K8sRequiredLabels, Name:all-must-have-owner, Namespace:
2021/06/28 11:24:22 Kind:K8sContainerLimits, Name:container-must-have-limits, Namespace:
```

Any ideas ? Maybe as I am running the Anthos/Google rebranded Gatekeeper but not sure why ?

**Comment by laimison** [comment]
hi @gfthybridlabs 

From the first look the issue is related with a missing namespace

I've submitted a PR to fix it

https://github.com/mcelep/opa-scorecard/pull/2

**Comment by gfthybridlabs** [comment]
Hi,

Thanks for looking at it. I did add that namespace entry for the service as I put this exporter + service in "monitoring" which is where my Prometheus stack lives (also amended the role/rolebinding parts).

I thought the missing namespace was related to the constraints but this line seems to suggest it should not matter

https://github.com/mcelep/opa-scorecard/blob/master/exporter-go/pkg/opa/constraints.go#L29

Although I am not a "go" coder so I might not be reading that correctly :)

Thanks

**Comment by Knappek** [comment]
@gfthybridlabs thanks for filing this issue and for trying out the project. Sorry for the late response. 
The empty namespace shouldn't be an issue, actually gatekeeper constraints are not namespaced that's why mostly these are empty. 500 errors could be anything and I would like to reproduce this issue. Could you briefly explain your setup, which Kubernetes version, which Gatekeeper version etc you are using?

**Comment by gfthybridlabs** [comment]
Hi,

Thanks. It is the version that comes with Anthos and is probably behind Gatekeeper upstream but I don't think there is too much different.

I will spin up a cluster tomorrow and let you know the specifics.

**Comment by Knappek** [comment]
@gfthybridlabs can you also verify that you are using `image: mcelep/opa_scorecard_exporter:v0.0.3`?

**Comment by gfthybridlabs** [comment]
Hi,

It's a bit hard to tell as the image name Anthos uses is internal to it/Google. The release notes for the latest suggest it's using this commit from upstream - https://github.com/open-policy-agent/gatekeeper/tree/f6c2fe8 which "looks" like v3.4.0

Yes I am using thet v0.0.3 image.

Still getting the 500's

Thanks.

**Comment by Knappek** [comment]
As you are directly curling the `opa-exporter` the OPA Gatekeeper version should not have any effect. 

Instead of  using the service's `ClusterIp`, are you able to port-forward the `opa-exporter` and do a curl on `http://localhost:9141/metrics`?

**Comment by gfthybridlabs** [comment]
Ah interesting port-forwarding shows:-

```
An error has occurred while serving metrics:

5 error(s) occurred:
* collected metric "opa_scorecard_violations" { label:<name:"kind" value:"AllowedServicePortName" > label:<name:"name" value:"port-name-constraint" > label:<name:"violating_kind" value:"Service" > label:<name:"violating_name" value:"argocd-dex-server" > label:<name:"violating_namespace" value:"argocd" > label:<name:"violation_enforcement" value:"dryrun" > label:<name:"violation_msg" value:"service port name missing prefix" > gauge:<value:1 > } was collected before with the same name and label values
* collected metric "opa_scorecard_violations" { label:<name:"kind" value:"AllowedServicePortName" > label:<name:"name" value:"port-name-constraint" > label:<name:"violating_kind" value:"Service" > label:<name:"violating_name" value:"argocd-dex-server" > label:<name:"violating_namespace" value:"argocd" > label:<name:"violation_enforcement" value:"dryrun" > label:<name:"violation_msg" value:"service port name missing prefix" > gauge:<value:1 > } was collected before with the same name and label values
* collected metric "opa_scorecard_violations" { label:<name:"kind" value:"AllowedServicePortName" > label:<name:"name" value:"port-name-constraint" > label:<name:"violating_kind" value:"Service" > label:<name:"violating_name" value:"argocd-repo-server" > label:<name:"violating_namespace" value:"argocd" > label:<name:"violation_enforcement" value:"dryrun" > label:<name:"violation_msg" value:"service port name missing prefix" > gauge:<value:1 > } was collected before with the same name and label values
* collected metric "opa_scorecard_violations" { label:<name:"kind" value:"AllowedServicePortName" > label:<name:"name" value:"port-name-constraint" > label:<name:"violating_kind" value:"Service" > label:<name:"violating_name" value:"argocd-server" > label:<name:"violating_namespace" value:"argocd" > label:<name:"violation_enforcement" value:"dryrun" > label:<name:"violation_msg" value:"service port name missing prefix" > gauge:<value:1 > } was collected before with the same name and label values
* collected metric "opa_scorecard_violations" { label:<name:"kind" value:"AllowedServicePortName" > label:<name:"name" value:"port-name-constraint" > label:<name:"violating_kind" value:"Service" > label:<name:"violating_name" value:"cnrm-manager-c3i0bj4gkgt3olgd5rbg" > label:<name:"violating_namespace" value:"cnrm-system" > label:<name:"violation_enforcement" value:"dryrun" > label:<name:"violation_msg" value:"service port name missing prefix" > gauge:<value:1 > } was collected before with the same name and label values
* 
```

Pod logs are as before:-
```
2021/07/06 07:32:54 Kind:AllowedServicePortName, Name:port-name-constraint, Namespace:
2021/07/06 07:32:56 Kind:K8sPSPAllowPrivilegeEscalationContainer, Name:psp-allow-privilege-escalation-container, Namespace:
2021/07/06 07:32:58 Kind:K8sRequiredLabels, Name:all-must-have-owner, Namespace:
2021/07/06 07:32:58 Kind:K8sContainerLimits, Name:container-must-have-limits, Namespace:
2021/07/06 07:32:59 Kind:K8sPSPPrivilegedContainer, Name:psp-privileged-container, Namespace:
2021/07/06 07:33:00 Tick at 2021-07-06 07:32:54.806508982 +0000 UTC m=+190.015056741
2021/07/06 07:33:00 Using incluster K8S client
2021/07/06 07:33:00 Using incluster K8S client
```

Thanks.

**Comment by Knappek** [comment]
@gfthybridlabs I am wondering whether we need to change something in the code... 

Can you show us the ConstraintTemplate for `AllowedServicePortName` please?

**Comment by gfthybridlabs** [comment]
Hi,

The Anthos one is a little different to the upstream one.

https://github.com/crcsmnky/gatekeeper-istio/blob/master/templates/port-name-template.yaml

It looks like this:-
```
spec:
  crd:
    spec:
      names:
        kind: AllowedServicePortName
      validation:
        openAPIV3Schema:
          properties:
            prefixes:
              items:
                type: string
              type: array
  targets:
  - rego: |
      package asm.guardrails.allowedserviceportname

      violation[{"msg": msg}] {
        service := input.review.object
        port := service.spec.ports[_]
        prefixes := input.parameters.prefixes

        not is_prefixed(port, prefixes)

        msg := "service port name missing prefix"
      }

      is_prefixed(port, prefixes) {
        prefix := prefixes[_]
        startswith(port.name, prefix)
      }
    target: admission.k8s.gatekeeper.sh
```

Thanks,

**Comment by Knappek** [comment]
I think it suffices if you replace 

```
violation[{"msg": msg}]
```

with

```
violation[{"msg": msg, "details": {"missing_prefixes": prefixes}}] {
```

as the `details` will make your metric unique having different `prefixes`. 

Can you try that?

**Comment by Knappek** [comment]
oh and also replace `msg` with

```
          msg := sprintf("service %v.%v port name missing prefix", 
            [service.metadata.name, service.metadata.namespace])
```

So basically use the upstream one :D

**Comment by gfthybridlabs** [comment]
Hi,

That doesn't appear to be it. Due to the way the operator works in Anthos it kept re-syncing the templates from upstream :)

So I disabled that which removed all constraint templates, added one in manually with the rego like upstream as you suggested and reapplied my constraint and the same occurs.

If I remove my constraint for that template then it all works. So obviously something in that. So I will play with that to see if it's an issue. It works as it is audited by gatekeeper just fine and reports on violations in the status output.

Without that template breaking things this is exactly what I need/want so many thanks for that.

```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedServicePortName
metadata:
  name: port-name-constraint
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
    # namespaces: ["default"]
    # alternatively you can limit it to namespaces where istio-injection is enabled
    namespaceSelector:
      matchExpressions:
        - key: istio.io/rev
          operator: In
          values: ["asm-178-8"]
    labelSelector:
      matchExpressions:
        - key: policy-controller
          operator: NotIn
          values: [ignore]
  parameters:
    prefixes: ["http-", "http2-", "grpc-", "mongo-", "redis-", "tcp-"]
```

I do get some panics and CrashLoopBacks in the opa-exporter pod when I change the templates around BTW.

```
panic: interface conversion: interface {} is nil, not float64

goroutine 20 [running]:
main.getConstraintViolations(0xc00010bf88, 0x2, 0x2, 0xc000940420, 0x2)
	/app/main.go:206 +0xe57
main.(*Exporter).startTimer.func1()
	/app/main.go:240 +0x18a
created by main.(*Exporter).startTimer
	/app/main.go:233 +0x5d
```

Thanks.

**Comment by Knappek** [comment]
> I do get some panics and CrashLoopBacks in the opa-exporter pod when I change the templates around BTW.I do get some panics and CrashLoopBacks in the opa-exporter pod when I change the templates around BTW.

oh okay, that's good to know. Can you please create another issue and elaborate what you mean with `when I change the templates around`? That would be much appreciated.

Regarding your issue with `AllowedServicePortName`: I think there's nothing we can do I'm afraid. I first thought we could also add the kubernetes service labels but that would still not make the metric unique as apparently it creates separate metrics for the same service with different violations.

Do you think we can close this issue for now?

**Comment by gfthybridlabs** [comment]
I would say so there is nothing that you can do. It's a trade-off between using this or my constraint as it all matches and works fine. Thanks for your help.
