### ISSUE TITLE
Publish the OPA dashboard to Grafana Dashboards

### ISSUE THREAD

**Issue by Hongbo-Miao** [mcelep/opa-scorecard#4]
It would be great to publish this OPA dashboard to [Grafana Dashboards](https://grafana.com/grafana/dashboards) so more people can know this exists 😃

**Comment by Knappek** [comment]
That's a great idea @Hongbo-Miao, I'll take that as a ToDo.

**Comment by Knappek** [comment]
Published: https://grafana.com/grafana/dashboards/14828
